### ISSUE TITLE
Package display container separatly

### ISSUE THREAD

**Issue by cdix** [plaintextpackets/netprobe_lite#12]
Is there a way to put the display (graphics) container in a separate compose bundle. That way I can run the probe in background without the overhead of the graphics. Then can start and stop the graphics to view results. I’m running this on a pi4/ubuntu server and need to conserve resources.

**Comment by Jeppedy** [comment]
I don't see why there would be an issue doing that.  Just create a second compose, clean up the two separate compose files so each has just what you need, declare the network as External in each.

**Comment by plaintextpackets** [comment]
You can, you'd need to:

1. Disable grafana in compose.yml (just comment out the block)
2. In the prometheus config in compose.yml, you need to add a port mapping like Grafana has, e.g.:
```    ports:
      - '3001:3000'
```

Then the app will be running and storing metrics in prometheus. You can then connect to the data source on the port you mapped using an external Grafana or other visualization tool.

**Comment by cdix** [comment]
Ok I’ll try that. Grafana see seems to make a substantial load on the pi, which is fine when I’m reviewing the data. I only need to look at it now and again so this should help.Thanks.“You can’t look down on someone without taking your eyes off God” Andy OdenhalRegards,Jay ♱On Apr 27, 2024, at 1:13 AM, Jeppedy ***@***.***> wrote:﻿
I don't see why there would be an issue doing that.  Just create a second compose, clean up the two separate compose files so each has just what you need, declare the network as External in each.

**Comment by plaintextpackets** [comment]
Any luck?

**Comment by MJ12358** [comment]
Working great with the following:

- Comment out Grafana in compose.yml

- Add ports to Prometheus in compose.yml:
```yml
ports:
    - '9090:9090'
```

- Add Prometheus data source to Grafana:
    - `<your-netprobe-prometheus-ip-addess>:9090`
    - Everything else default (No authentication, POST etc)

- Import Grafana dashboard config:
    - [Download from repo](https://github.com/plaintextpackets/netprobe_lite/blob/master/config/grafana/dashboards/netprobe.json)
    - Modify data source uid (this occurs some 23 times in that file):
    ```json
      "datasource": {
        "type": "prometheus",
        "uid": "<your-prometheus-data-source-id>"
      }
    ```

**Comment by cdix** [comment]
Can confirm - works. 

Thanks for the help - I’m only a casual Docker user so I didn’t want to jump in unaided

**Comment by plaintextpackets** [comment]
Awesome - will close this one for now
