### ISSUE TITLE
How can i see Packet loss per IP or domain

### ISSUE THREAD

**Issue by MatejsLab** [plaintextpackets/netprobe_lite#14]
Hi

Now i am surprised that yesterday i had zero packet loss on chart, but today it is all the time around 1to 5% on netstat chart, which looks severe.

How do i know what test website isnt repllying, as it shows like internet is bad, but i suspect that one of the test websites is iffy as its saturday.

How can i confirm that there is no severe issue with my internet, as UptimeKuma says 100% to  google and synology servers, and my internet experience today is fine.

Hwo can i display metrics per IP or domain of monitors for packet loss, so i can know the cause.

Thanks, Matej

![Screenshot_20240427_121517_Brave](https://github.com/plaintextpackets/netprobe_lite/assets/28715097/72471d8f-71ae-44b4-b5ef-a243ae19b93c)
![Screenshot_20240427_110934_Brave](https://github.com/plaintextpackets/netprobe_lite/assets/28715097/01bcace0-8b99-405a-af97-11a80bc17cf9)

**Comment by plaintextpackets** [comment]
Unfortunately as it's written now the packet loss from all of the anchors is aggregated before it gets sent to prometheus / grafana. What you could do temporarily is a Wireshark capture to look at which ICMP pings are failing consistently.

**Comment by MatejsLab** [comment]
Indeed there are internet issues, otherwise i wouldn't need netprobe lite.
Many are droping.

I directed my router to 4G backup and packet loss went to 0% and stays
there for long time, so my fiber optics ISP or modem actually may have an
issue that is intermitent, but today it was obvious, as connecting back to
fiber packet loss comes back.
I had fiber and 4G on failover, The annoyance is that even loadbalancing
both connections on Unifi doesnt solve an issue. Only full switchover to my
4G backup is great when there is no peak hours.

I may have to call on Telekom or T2 and tell them they have to solve this.
The fiber is leased from Telekom and we have T2, before we had Telemach
over same Telekom fiber, therefore issues persist.

Telemach the previous ISP they said it is normal, I may have to do periodic
traceroute to pinpoint them the problematic node?

Thanks for guidance, the tool is indeed usefull.

Matej

V sob., 27. apr. 2024, 17:27 je oseba plaintextpackets <
***@***.***> napisala:

**Comment by plaintextpackets** [comment]
I'm working on a version that lets you break out the packet loss, latency and jitter by destination:

<img width="1504" alt="Capture" src="https://github.com/plaintextpackets/netprobe_lite/assets/157658346/a9e1b507-96d4-4a6f-aaa9-4fefaf17dac5">

I should have this ready soon

**Comment by plaintextpackets** [comment]
Fixed with https://github.com/plaintextpackets/netprobe_lite/pull/20
