### ISSUE TITLE
Config changes stops Graphana displaying data

### ISSUE THREAD

**Issue by RemcoVroman** [plaintextpackets/netprobe_lite#26]
Hi, first of all great job !

I'm running Almalinux 9 and Python 3.9.18. 

Installing this tool in a venv en start it, it runs perfectly. However when I change DNS_NAMESERVER_4_IP to my own address and change one of the sites, data is being collected (logging is telling me). But Graphana stops displaying data. 

Any suggestions how to find the issue or how to fix this ?

Best regards,
Remco

**Comment by plaintextpackets** [comment]
Can you post your modified .env file

**Comment by RemcoVroman** [comment]
[env.txt](https://github.com/plaintextpackets/netprobe_lite/files/15177502/env.txt)
Sure, it should be attached.

**Comment by plaintextpackets** [comment]
Ah I see the issue:

DNS_TEST_SITE="My_DNS_Server" # This is the site used in the DNS test

This value should be a domain name. This is the domain which the DNS test queries to measure latency. I think the default is google.com. You can use another domain but I would use a well-known domain with reliable name servers

**Comment by RemcoVroman** [comment]
That seem to be the problem. I misunderstand the purpose of this configuration item. Thanks !
