### ISSUE TITLE
In the latest image the package loss is reporting extremly high

### ISSUE THREAD

**Issue by tradosh** [plaintextpackets/netprobe_lite#34]
I have stable Fibre connection, I have run tests from inside all the docker images, and they all come back with a very quick response (under 10ms for almost all) and no real changes or drop, however for some reason the system reports that it's losing 52% of items - I tried to look into the config but can't find anything that would point me to what is causing that issue. Any suggestions would be appreciated (all other values show correctly, so latency 6.4ms, jitter is 0.3ms, DNS response 1ms)

**Comment by securedpackets** [comment]
I’d be happy to help. What version are you running? Also can you post some
screenshots

**Comment by tradosh** [comment]
Average Package Loss is using this: Network_Stats{type="loss", target="all"}
And Prmetheus returns this when doing Network_Stats

<html>
<body>

Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="youtube.com", type="latency"} | 6.445
-- | --
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="youtube.com", type="loss"} | 62
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="youtube.com", type="jitter"} | 0.324
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="facebook.com", type="latency"} | 6.347
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="facebook.com", type="loss"} | 54
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="facebook.com", type="jitter"} | 0.465
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="google.com", type="latency"} | 6.569
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="google.com", type="loss"} | 38
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="google.com", type="jitter"} | 0.411
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="all", type="latency"} | 6.453666666666667
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="all", type="loss"} | 51.333333333333336
Network_Stats{group="Home network", instance="presentation:5000", job="prometheus", site_id="f0ac2f33-1a20-471d-b430-d905900e0e71", target="all", type="jitter"} | 0.39999999999999997


</body>
</html>

**Comment by plaintextpackets** [comment]
It appears like your packet loss when hitting Youtube is higher than all the others - what happens when you ping Youtube.com manually? 
target="youtube.com", type="loss"} | 62

**Comment by plaintextpackets** [comment]
Please adjust by removing youtube from your sites list, or contacting your ISP to understand why Youtube is showing loss
