### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by blimeybloke** [plaintextpackets/netprobe_lite#35]
Running this on Ubuntu 20.
Running Docker with portainer on top.

When I try to start it, it gives an error:
/bin/bash: ./entrypoint.sh: No such file or directory

Any advice or tips?

Thanks

**Comment by plaintextpackets** [comment]
See this issue https://github.com/plaintextpackets/netprobe_lite/issues/29

Haven't fixed it yet but will collapse issues to one
