### ISSUE TITLE
Unauthorized and constant reloading

### ISSUE THREAD

**Issue by dinasty02091994** [plaintextpackets/netprobe_lite#37]
When deploying via docker-compose grafana will give you constant "Unauthorized" messages wich will trigger reloads when viewing the dashboard that's been provisioned. 

In the current state it is more or less unusable. 
I've been fiddling around with this and changing the grafana version to 10.1.6 solves the problem completely. 

if you open the web developer console you will see the following messages spammed: 
msg=Unauthorized error="user token not found"

**Comment by plaintextpackets** [comment]
What version of netprobe are you using? Also what version of docker?

No other reports of this so far so curious

**Comment by dinasty02091994** [comment]
I did a git clone of your repo so it must be the latest version i believe. According to the compose.yml file it should be this version: 
"plaintextpackets/netprobe:latest"
The docker version i am running is the following: Docker version 26.1.2, build 211e74b240

**Comment by plaintextpackets** [comment]
Can you try deleting your docker volumes and relaunching?

**Comment by dinasty02091994** [comment]
I've tried that several times but to no avail unfortunately. Here's a clip of when i start it up for the first time via docker-compose. Before running the command i've made sure that no volumes is present. 
Please not that i am not pressing any keys once i've signed in to grafana. 

[Screencast from 2024-05-11 11-32-47.webm](https://github.com/plaintextpackets/netprobe_lite/assets/28081968/d0199f49-7745-414e-b7eb-ab26bc8c403b)

**Comment by plaintextpackets** [comment]
I'll text it out, for temporary relief you can change the grafana version in compose.yml to grafana:10.1.6 instead of grafana:latest

**Comment by plaintextpackets** [comment]
Also do you see any errors in the stdout or when doing 'docker logs netprobe-grafana'?

**Comment by plaintextpackets** [comment]
Any luck?

**Comment by plaintextpackets** [comment]
Going to close this for now, if you still experience the issue please join the discord to discuss
