### ISSUE TITLE
DNS, Encrypted, my_dns_latency error

### ISSUE THREAD

**Issue by pumalife** [plaintextpackets/netprobe_lite#38]
Not sure what the issue is. I def had to go through a few steps to get things to work.
had to disable TinyFirewall to get docker to load, then working... I ran into this issue (see log file below)
docker compose up runs and works and then log outputs this on repeat. I did have encrypted DNS in windows natively, i disabled it and reset to auto DHCP DNS, the DNS returned to be default 1.1.1.1 9.9.9.9 (even restarting it didnt reset to my gateway), but it clearly says unencrypted now.
so this error log looks like DoH / encrypted DNS, but not sure what else to do that is the issue.

Log

netprobe-probe         | Error performing DNS resolution on ('Google_DNS', '8.8.8.8')
netprobe-probe         | The resolution lifetime expired after 5.101 seconds: Server Do53:8.8.8.8@53 answered The DNS operation timed out.
netprobe-probe         | Error performing DNS resolution on ('Quad9_DNS', '9.9.9.9')
netprobe-probe         | The resolution lifetime expired after 5.106 seconds: Server Do53:9.9.9.9@53 answered The DNS operation timed out.
netprobe-probe         | Error performing DNS resolution on ('CloudFlare_DNS', '1.1.1.1')
netprobe-probe         | The resolution lifetime expired after 5.106 seconds: Server Do53:1.1.1.1@53 answered The DNS operation timed out.
netprobe-probe         | Error performing DNS resolution on ('My_DNS_Server', '8.8.8.8')
netprobe-probe         | The resolution lifetime expired after 5.106 seconds: Server Do53:8.8.8.8@53 answered The DNS operation timed out.
netprobe-presentation  | Traceback (most recent call last):
netprobe-presentation  |   File "/usr/lib/python3.12/wsgiref/handlers.py", line 137, in run
netprobe-presentation  |     self.result = application(self.environ, self.start_response)
netprobe-presentation  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/exposition.py", line 128, in prometheus_app
netprobe-presentation  |     status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
netprobe-presentation  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/exposition.py", line 104, in _bake_output
netprobe-presentation  |     output = encoder(registry)
netprobe-presentation  |              ^^^^^^^^^^^^^^^^^
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
netprobe-presentation  |     for metric in registry.collect():
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/registry.py", line 97, in collect
netprobe-presentation  |     yield from collector.collect()
netprobe-presentation  |   File "/netprobe_lite/presentation.py", line 106, in collect
netprobe-presentation  |     if my_dns_latency / threshold_dns_latency >= 1:
netprobe-presentation  |        ^^^^^^^^^^^^^^
netprobe-presentation  | UnboundLocalError: cannot access local variable 'my_dns_latency' where it is not associated with a value

**Comment by plaintextpackets** [comment]
Do you see anything on the dashboard? Or are all metrics failing?

**Comment by plaintextpackets** [comment]
Going to close this

If you still have the issue please re-open the issue or join the discord to discuss
