### ISSUE TITLE
Netprobe uses same port as Uptime Kuma

### ISSUE THREAD

**Issue by Unclerojelio** [plaintextpackets/netprobe_lite#4]
```
Error response from daemon: driver failed programming external connectivity on endpoint netprobe-grafana (b4ac30551a4e633f7cd61067515636022e2351fad2ad2457ecb45e5c6a23996b): Bind for 0.0.0.0:3001 failed: port is already allocated
```

**Comment by plaintextpackets** [comment]
Change your docker compose file:

  grafana:
    restart: always
    image: grafana/grafana-enterprise
    container_name: netprobe-grafana
    volumes:
      - ./config/grafana/datasources/automatic.yml:/etc/grafana/provisioning/datasources/automatic.yml
      - ./config/grafana/dashboards/main.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./config/grafana/dashboards/netprobe.json:/var/lib/grafana/dashboards/netprobe.json
    ports:
      **- '3001:3000'** <--------- change this
    networks:
      - custom_network  # Attach to the custom network

**Comment by dpd696** [comment]
Also check your docker network:


version: '3.8'  # Use the desired Docker Compose version

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16 <------------- Might need to change this if a container is using this subnet

**Comment by plaintextpackets** [comment]
I've now added instructions for this to the Readme as well

**Comment by MatejsLab** [comment]
Thanks for help on installing, it is working now, i had to copy the repo in docker folder and set my port for grafana, and now it works on Synology container manager fine.

Is there any concern that Netprobe along with Uptime Kuma monitroing 10 devices every minute, would use HDD on NAS excesively?

Cheers Matej

**Comment by plaintextpackets** [comment]
No concern for Netprobe at least, the storage requirement is minimal. Prometheus collects the metrics once every 30s and there are only a handful of metrics
