### ISSUE TITLE
Exited with code 1 & 2

### ISSUE THREAD

**Issue by jervis0891** [plaintextpackets/netprobe_lite#42]
netprobe-grafana exited with code 1
netprobe-prometheus    | ts=2024-05-14T19:34:12.604Z caller=main.go:573 level=info msg="No time or size retention was set so using the default time retention" duration=15d
netprobe-prometheus    | ts=2024-05-14T19:34:12.605Z caller=main.go:617 level=info msg="Starting Prometheus Server" mode=server version="(version=2.52.0, branch=HEAD, revision=879d80922a227c37df502e7315fad8ceb10a986d)"
netprobe-prometheus    | ts=2024-05-14T19:34:12.605Z caller=main.go:622 level=info build_context="(go=go1.22.3, platform=linux/amd64, user=root@1b4f4c206e41, date=20240508-21:56:43, tags=netgo,builtinassets,stringlabels)"
netprobe-prometheus    | ts=2024-05-14T19:34:12.605Z caller=main.go:623 level=info host_details="(Linux 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64 69e28a7855d4 (none))"
netprobe-prometheus    | ts=2024-05-14T19:34:12.605Z caller=main.go:624 level=info fd_limits="(soft=1048576, hard=1048576)"
netprobe-prometheus    | ts=2024-05-14T19:34:12.605Z caller=main.go:625 level=info vm_limits="(soft=unlimited, hard=unlimited)"
netprobe-prometheus    | ts=2024-05-14T19:34:12.607Z caller=query_logger.go:93 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
netprobe-prometheus    | panic: Unable to create mmap-ed active query log
netprobe-prometheus    | 
netprobe-prometheus    | goroutine 1 [running]:
netprobe-prometheus    | github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7ffc58e61f79, 0xb}, 0x14, {0x44aa9e0, 0xc00055cc30})
netprobe-prometheus    |        /app/promql/query_logger.go:123 +0x425
netprobe-prometheus    | main.main()
netprobe-prometheus    |        /app/cmd/prometheus/main.go:748 +0x82fe
netprobe-prometheus exited with code 2

Could you point in the right direction to solve this?

**Comment by plaintextpackets** [comment]
Have you modified the .env file at all?

**Comment by plaintextpackets** [comment]
Please join the Discord if you want to troubleshoot further
