### ISSUE TITLE
Running netprobe with external Grafana instance

### ISSUE THREAD

**Issue by mobrembski** [plaintextpackets/netprobe_lite#43]
Hi!

I have a question, i'm interested in running netprobe, but i have an already instance of Grafana running on my net (running on Home Assistant, different host that is running docker). I'd like to include netprobe dashboard to my already running instance.
The point is, i'm not super familiar with docker compose files. Are you able to help me?

I assume that i need to (obviously) import dashboards definitions from repo to my grafana, comment grafana section in compose file.
Then instruct somehow that prometheus should be exposed to my internal network.

But what worries me the most, is that i cant figure out where Grafana in this repo keeps URL for datasource?

**Comment by plaintextpackets** [comment]
You can achieve this by:

1. Modifying compose.yaml to add a port mapping for prometheus:



  prometheus:
    restart: always
    container_name: netprobe-prometheus
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Persistent local storage for Prometheus data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - netprobe-net
    ports:
      - 'XXXX:'9090'
      
... where XXXX is the port you want to expose, 9090 is the default prometheus port



2. Remove the grafana config from the compose file altogether


This should do it
