### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by mrpops2ko** [plaintextpackets/netprobe_lite#44]
hi i recently stumbled upon your video, and after having successfully diagnosed problems with my own ISP who erroneously claimed it was my own fault I thought maybe they could be included too. 

I noticed that during periods of time, my connection would drop but only aspects of it, for example PPPoE would remain connected. 

I managed to find out who the culprit was, by being lucky enough to run a trace route during the periods where it wouldn't pass traffic. 

This information alongside a total bandwidth usage would be extremely useful inclusions. SNMP / NetFlow support would also be a nice inclusion but I doubt many are making use of that. 

Running constant trace routes every 5 seconds or something? then if anybody experiences the same problems that I did, they would be able to look back and see which parts of their ISP weren't properly passing traffic from one to the other.

**Comment by plaintextpackets** [comment]
I am actually working on a module to do traceroutes to the target sites every 30 seconds, but still needs some testing.

WRT snmp or netflow I thought about it as well, you're right that would be too advanced for the average user and would make the tool more complicated.

Thank you for the suggestions!

**Comment by plaintextpackets** [comment]
Will add these notes to backlog
