### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by xvilo** [plaintextpackets/netprobe_lite#52]
I run a Kubernetes cluster at home (microk8s) and I'm thinking of creating a helm chart out of this repository so we can easily run it in there instead of having to deal with `docker compose`. At this point I'm wonder if maybe somebody already did this, and if not, if people might be interested in running this on Kubernetes.

**Comment by securedpackets** [comment]
I would love to see it, I don’t have a k8s cluster at home just at work so
haven’t been able to test the config. No one else bas requested yet

**Comment by xvilo** [comment]
Alright, in that case, do you want to see it in this repo, a new repo of your own or shall I add it to my collection of helm charts located at https://github.com/xvilo/helm-charts ?

**Comment by securedpackets** [comment]
If you wanted to add it to yours I can link to it in the readme

**Comment by plaintextpackets** [comment]
Just let me know when your repo is ready
