### ISSUE TITLE
Support for the old Raspberry Pi Model B

### ISSUE THREAD

**Issue by 19Vik19** [plaintextpackets/netprobe_lite#54]
Hey there, 
I have two old raspberry pi model B laying around and I thought I could use one for your project. 
I installed the newest version of Raspberry Pi OS (Legacy, 32-Bit) Lite and Docker Engine. After configuring the .env file I tried to “docker compose up” but it stopped with :

[+] Running 4/6
 ⠏ grafana Pulling                                                                                                 6.9s
 ✘ redis Error        context canceled                                                                             6.9s
 ⠇ netprobe Pulling                                                                                                6.9s
 ✘ speedtest Error    context canceled                                                                             6.9s
 ✘ presentation Error context canceled                                                                             6.8s  
✘ prometheus Error   context canceled                                                                             6.8s
no matching manifest for linux/arm/v6 in the manifest list entries

Is there any way around this? Is there any way you could add support for such old devices or is it time to upgrade ? :D

Thanks a lot and have a great day!

**Comment by plaintextpackets** [comment]
I know it does work on the RPi 4 and I do now have an ARM-compatible image, but the device may just be too old :/
