### ISSUE TITLE
Network Pool overlap

### ISSUE THREAD

**Issue by ceramicv** [plaintextpackets/netprobe_lite#8]
On trying to to a "docker compose up -d" I get the following error:

Network netprobe_custom_network Error
failed to create network netprobe_custom_network: Error response from daemon: Pool overlaps with other one on this address space

**Comment by plaintextpackets** [comment]
Are you running any other docker apps locally?

**Comment by ceramicv** [comment]
Did a docker network ls and then an inspect and found that 172.21 conflicted with Heimdall whioch did not define a subnet, so did a docker compose down on that, then let netprobe up to take 172.21, then did a docker compose up on heimdall which assigned a free subnet. All good now.

**Comment by Jeppedy** [comment]
Since NetProbe doesn't care the network it's on, as long as all containers are on the SAME network, do we really even need the network declaration?  I removed all references to Network, and since all within one Docker Compose file gets the same default network, all is still working fine.
